"""initial schema

Revision ID: 0001
Revises:
"""

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_cache",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False),
        sa.PrimaryKeyConstraint("content_hash", "embedding_model", name=op.f("pk_embedding_cache")),
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("github_repo_id", sa.BigInteger(), nullable=False),
        sa.Column("owner", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("installation_id", sa.BigInteger(), nullable=True),
        sa.Column("default_branch", sa.String(length=255), nullable=False),
        sa.Column("private", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repositories")),
        sa.UniqueConstraint("github_repo_id", name=op.f("uq_repositories_github_repo_id")),
        sa.UniqueConstraint("owner", "name", name=op.f("uq_repositories_owner")),
    )
    op.create_table(
        "code_chunks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("blob_sha", sa.String(length=40), nullable=False),
        sa.Column("chunker_version", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("symbol", sa.Text(), nullable=True),
        sa.Column("qualified_name", sa.Text(), nullable=True),
        sa.Column("symbol_type", sa.String(length=32), nullable=False),
        sa.Column("parent_symbol", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("signature", sa.Text(), nullable=True),
        sa.Column("imports", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("called_names", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("bases", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column(
            "fts",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(qualified_name,'') || ' ' || coalesce(signature,'') || ' ' || content)",
                persisted=True,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_code_chunks_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_chunks")),
        sa.UniqueConstraint(
            "repository_id",
            "blob_sha",
            "chunker_version",
            "start_line",
            "symbol_type",
            "qualified_name",
            name="uq_code_chunks_identity",
        ),
    )
    op.create_index(
        "ix_code_chunks_called_names",
        "code_chunks",
        ["called_names"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_code_chunks_embedding_hnsw",
        "code_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_code_chunks_fts", "code_chunks", ["fts"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_code_chunks_imports", "code_chunks", ["imports"], unique=False, postgresql_using="gin"
    )
    op.create_index(
        "ix_code_chunks_qname_trgm",
        "code_chunks",
        ["qualified_name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"qualified_name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_code_chunks_repo_blob", "code_chunks", ["repository_id", "blob_sha"], unique=False
    )
    op.create_table(
        "repository_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("parent_snapshot_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("file_count", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("chunker_version", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_snapshot_id"],
            ["repository_snapshots.id"],
            name=op.f("fk_repository_snapshots_parent_snapshot_id_repository_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_repository_snapshots_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository_snapshots")),
        sa.UniqueConstraint(
            "repository_id",
            "commit_sha",
            "embedding_model",
            "chunker_version",
            name=op.f("uq_repository_snapshots_repository_id"),
        ),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("delivery_id", sa.String(length=64), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=True),
        sa.Column("repository_id", sa.UUID(), nullable=True),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=True),
        sa.Column("review_job_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_webhook_deliveries_repository_id_repositories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("delivery_id", name=op.f("pk_webhook_deliveries")),
    )
    op.create_table(
        "review_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repository_id", sa.UUID(), nullable=False),
        sa.Column("pull_number", sa.Integer(), nullable=False),
        sa.Column("base_sha", sa.String(length=40), nullable=True),
        sa.Column("head_sha", sa.String(length=40), nullable=False),
        sa.Column("snapshot_id", sa.UUID(), nullable=True),
        sa.Column("installation_id", sa.BigInteger(), nullable=True),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("delivery_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("github_review_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repositories.id"],
            name=op.f("fk_review_jobs_repository_id_repositories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["repository_snapshots.id"],
            name=op.f("fk_review_jobs_snapshot_id_repository_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_jobs")),
    )
    op.create_index("ix_review_jobs_status", "review_jobs", ["status"], unique=False)
    op.create_index(
        "uq_review_jobs_live_head",
        "review_jobs",
        ["repository_id", "pull_number", "head_sha"],
        unique=True,
        postgresql_where=sa.text("status NOT IN ('FAILED','CANCELLED','STALE')"),
    )
    op.create_table(
        "snapshot_files",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("blob_sha", sa.String(length=40), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["repository_snapshots.id"],
            name=op.f("fk_snapshot_files_snapshot_id_repository_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "path", name=op.f("pk_snapshot_files")),
    )
    op.create_index("ix_snapshot_files_blob_sha", "snapshot_files", ["blob_sha"], unique=False)
    op.create_table(
        "review_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_job_id", sa.UUID(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("line_start", sa.Integer(), nullable=False),
        sa.Column("line_end", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=5), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_quote", sa.Text(), nullable=False),
        sa.Column("suggested_fix", sa.Text(), nullable=True),
        sa.Column("replacement_code", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reject_reason", sa.String(length=64), nullable=True),
        sa.Column("github_comment_id", sa.BigInteger(), nullable=True),
        sa.Column("pass_name", sa.String(length=32), nullable=False),
        sa.Column("context_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_job_id"],
            ["review_jobs.id"],
            name=op.f("fk_review_findings_review_job_id_review_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_findings")),
    )
    op.create_index(
        "ix_review_findings_fingerprint", "review_findings", ["fingerprint"], unique=False
    )
    op.create_index(
        "ix_review_findings_job_status",
        "review_findings",
        ["review_job_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_review_findings_job_status", table_name="review_findings")
    op.drop_index("ix_review_findings_fingerprint", table_name="review_findings")
    op.drop_table("review_findings")
    op.drop_index("ix_snapshot_files_blob_sha", table_name="snapshot_files")
    op.drop_table("snapshot_files")
    op.drop_index(
        "uq_review_jobs_live_head",
        table_name="review_jobs",
        postgresql_where=sa.text("status NOT IN ('FAILED','CANCELLED','STALE')"),
    )
    op.drop_index("ix_review_jobs_status", table_name="review_jobs")
    op.drop_table("review_jobs")
    op.drop_table("webhook_deliveries")
    op.drop_table("repository_snapshots")
    op.drop_index("ix_code_chunks_repo_blob", table_name="code_chunks")
    op.drop_index(
        "ix_code_chunks_qname_trgm",
        table_name="code_chunks",
        postgresql_using="gin",
        postgresql_ops={"qualified_name": "gin_trgm_ops"},
    )
    op.drop_index("ix_code_chunks_imports", table_name="code_chunks", postgresql_using="gin")
    op.drop_index("ix_code_chunks_fts", table_name="code_chunks", postgresql_using="gin")
    op.drop_index(
        "ix_code_chunks_embedding_hnsw",
        table_name="code_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_code_chunks_called_names", table_name="code_chunks", postgresql_using="gin")
    op.drop_table("code_chunks")
    op.drop_table("repositories")
    op.drop_table("embedding_cache")
    # ### end Alembic commands ###
