"""File classification: language, test/generated/lockfile detection."""

import re
from pathlib import PurePosixPath

LANGUAGES = {
    ".py": "python", ".pyi": "python", ".js": "javascript", ".jsx": "javascript",
    ".ts": "typescript", ".tsx": "typescript", ".go": "go", ".java": "java", ".rb": "ruby",
    ".rs": "rust", ".sql": "sql", ".yml": "yaml", ".yaml": "yaml", ".toml": "toml",
    ".json": "json", ".md": "markdown", ".sh": "shell", ".ini": "ini", ".cfg": "ini",
}  # fmt: skip

LOCKFILES = {
    "poetry.lock", "uv.lock", "Pipfile.lock", "package-lock.json", "yarn.lock",
    "pnpm-lock.yaml", "Cargo.lock", "go.sum", "Gemfile.lock", "composer.lock",
}  # fmt: skip

_GENERATED_PATH = re.compile(
    r"(^|/)(dist|build|node_modules|vendor|third_party|__pycache__|\.venv|venv|coverage)/"
    r"|\.min\.(js|css)$|_pb2(_grpc)?\.pyi?$|\.generated\.|(^|/)generated/|\.snap$"
)
_TEST_PATH = re.compile(
    r"(^|/)(tests?|__tests__|spec)/|(^|/)test_[^/]*\.py$|_test\.(py|go)$|\.(test|spec)\.[jt]sx?$|(^|/)conftest\.py$"
)
_BINARY_EXT = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".ico",
    ".pdf",
    ".zip",
    ".gz",
    ".tar",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".so",
    ".dll",
    ".exe",
    ".pyc",
    ".jar",
    ".whl",
    ".bin",
}
GENERATED_MARKERS = (
    "# Code generated",
    "// Code generated",
    "DO NOT EDIT",
    "@generated",
    "Generated by the protocol buffer compiler",
)


def detect_language(path: str) -> str | None:
    return LANGUAGES.get(PurePosixPath(path).suffix.lower())


def is_test_path(path: str) -> bool:
    return bool(_TEST_PATH.search(path))


def is_generated_path(path: str) -> bool:
    return bool(_GENERATED_PATH.search(path))


def is_lockfile(path: str) -> bool:
    return PurePosixPath(path).name in LOCKFILES


def is_binary_path(path: str) -> bool:
    return PurePosixPath(path).suffix.lower() in _BINARY_EXT


def has_generated_marker(head_of_file: str) -> bool:
    head = head_of_file[:600]
    return any(m in head for m in GENERATED_MARKERS)
