from app.indexing.ignore import IgnoreRules, should_index


def ok(path: str, data: bytes = b"x = 1\n", rules: IgnoreRules | None = None) -> tuple[bool, str]:
    return should_index(path, data, rules or IgnoreRules())


def test_defaults_ignored() -> None:
    for p in ["node_modules/a/index.js", ".venv/lib/x.py", "dist/app.js", "vendor/x/y.go",
              "app/__pycache__/m.py", "static/app.min.js", ".env"]:  # fmt: skip
        assert not ok(p)[0], p


def test_env_example_allowed_if_supported_type() -> None:
    assert not ok(".env.example")[0]  # no language mapping: unsupported rather than ignored
    assert ok("app/main.py")[0]


def test_gitignore_respected() -> None:
    rules = IgnoreRules("secrets/\n*.local.py\n")
    assert ok("secrets/keys.py", rules=rules) == (False, "ignored")
    assert ok("app/x.local.py", rules=rules)[0] is False
    assert ok("app/x.py", rules=rules)[0] is True


def test_binary_large_generated_lockfile() -> None:
    assert ok("a.py", b"\x00\x01binary")[1] == "binary"
    assert ok("a.py", b"x" * (600 * 1024))[1] == "too_large"
    assert ok("a.py", b"# Code generated by protoc. DO NOT EDIT.\nx=1")[1] == "generated"
    assert ok("uv.lock")[0] is False and ok("logo.png", b"abc")[0] is False
